### ISSUE TITLE
Question to tsv data...

### ISSUE THREAD

**Issue by Meywether** [entitize/Fakeddit#4]
Dear entitize,
thanks for the great dataset.
I am a little bit confused, because after switich from the before 12.03 dataset to the after 12.03 dataset, my pipelines broke at several pooints.

May I ask you kindly to explain some points:

For example in the validate.tsv (happens to all of the three files):

- What is the use of the first 4 columns with the column header Unnamed?
![image](https://user-images.githubusercontent.com/39849054/79681753-d6a42c00-821c-11ea-8cec-5149d9a805f7.png)

- What is the reason behing that sometimes author, title and clean_title values are NaNs?

Thanks a lot! 

Best regards
Meywether

**Comment by entitize** [comment]
Hi Meywether,

You can ignore the first four columns – they don't mean anything. I can make this clear in the README. 

The reason that the title and clean_title values are sometimes NAN is because sometimes these fields are blank. (for example, some posts don't have a title like the ones from psbattle_artwork). 

If you're using pandas, you can do something like the following to replace all the NaNs.

`pd.read_csv(data_dir + "train.tsv", delimiter="\t").replace(np.nan, '', regex=True)`

**Comment by Meywether** [comment]
Hello entitize,
thanks for the quick answer and the code:
Prevously I did this:

`df_val_original = df_val_original[~df_val_original['title'].str.contains('NaN')]`

Thanks a lot :)
